require:
  rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'Guardfile'
##
## Layout
##
Layout/LineLength:
  Max: 120

##
## Style
##
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
